export const SkillsList = [
  { content: "React", id: 1 },
  { content: "React Router", id: 2 },
  { content: "Promises, Async/Await", id: 3 },
  { content: "React Hooks", id: 4 },
  { content: "Redux-Saga", id: 5 },
  { content: "GitHub Pull Requests & Review", id: 6 },
  { content: "Redux (Toolkit)", id: 7 },
  { content: "Teamwork", id: 8 },
  { content: "Trello", id: 9 },
  { content: "Git", id: 10 },
  { content: "CSS Grid", id: 11 },
  { content: "CSS Flexbox", id: 12 },
  { content: "Immutability", id: 13 },
  { content: "Error handling", id: 14 },
  { content: "NPM", id: 15 },
  { content: "JavaScript: ES6+", id: 16 },
  { content: "Working with API (fetch, axios)", id: 17 },
  { content: "Semantic & accessible HTML", id: 18 },
  { content: "CSS BEM convention", id: 19 },
  { content: "Responsive Web Design", id: 20 },
  { content: "Markdown", id: 21 },
  { content: "Scrum", id: 22 },
];

export const SkillsListToLern = [
  { content: "React Context", id: 1 },
  { content: "Cypress", id: 2 },
  { content: "Node.js", id: 3 },
  { content: "Unit testing", id: 4 },
  { content: "TypeScript", id: 5 },
  { content: "JS classes", id: 6 },
];
